services:
  neo4j:
    container_name: neo4j
    image: ${NEO4J_IMAGE:-docker.io/neo4j:2026.09.0-community@sha256:91fb0bf237c41b7b3dcbe84703aa0b82e0d7d067b16e1c8ab21f03fc679edf4e}
    environment:
      - NEO4J_AUTH=neo4j/hibernate_orm_test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
    ports:
      - "7474:7474"
      - "7687:7687"