services:
  neo4j:
    container_name: neo4j
    image: ${NEO4J_IMAGE:-docker.io/neo4j:2026.06.0-community@sha256:ba2b859bdbe7017a9baa1a7b5681ac9732198753719b0a502e3645feddfdec72}
    environment:
      - NEO4J_AUTH=neo4j/hibernate_orm_test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=\[\"apoc\"\]
    ports:
      - "7474:7474"
      - "7687:7687"