services:
  neo4j:
    container_name: neo4j
    image: ${NEO4J_IMAGE:-docker.io/neo4j:2026.07.1-community@sha256:dbc377fb9cd8fe8dabc19d3041b197d5ca0ef8bae514cea175b8df265e5b7a76}
    environment:
      - NEO4J_AUTH=neo4j/hibernate_orm_test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
    ports:
      - "7474:7474"
      - "7687:7687"