sonar.projectName=Hibernate NoSQL
sonar.projectDescription=Idiomatic persistence for Java and NoSQL databases.

sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.modules=hibernate-nosql-core,hibernate-milvus,hibernate-neo4j

hibernate-core.sonar.projectName=Hibernate NoSQL - Core
hibernate-core.sonar.projectBaseDir=hibernate-nosql-core
hibernate-core.sonar.sources=src/main/java
hibernate-core.sonar.tests=src/test/java
hibernate-core.sonar.java.binaries=target/classes/java/main

hibernate-envers.sonar.projectName=Hibernate NoSQL - Milvus
hibernate-envers.sonar.projectBaseDir=hibernate-milvus
hibernate-envers.sonar.sources=src/main/java
hibernate-envers.sonar.tests=src/test/java
hibernate-envers.sonar.java.binaries=target/classes/java/main

hibernate-graalvm.sonar.projectName=Hibernate NoSQL - Neo4j
hibernate-graalvm.sonar.projectBaseDir=hibernate-neo4j
hibernate-graalvm.sonar.sources=src/main/java
hibernate-graalvm.sonar.tests=src/test/java
hibernate-graalvm.sonar.java.binaries=target/classes/java/main
