[[compatibility]]
== Compatibility

[[compatibility-dependencies]]
=== [[system-requirements]] Dependencies

Hibernate NoSQL {fullVersion} requires the following dependencies (among others):

.Compatible versions of dependencies
[cols="h,^1", stripes=none]
|===============
| h|Version
|Java Runtime
|{javaCompatibleVersions}
|https://hibernate.org/orm/[Hibernate ORM]
|{ormVersion}
|JDBC (bundled with the Java Runtime)
|{jdbcVersion}
|===============

[TIP]
====
Find more information for all versions of Hibernate NoSQL on our
https://hibernate.org/nosql/releases/#compatibility-matrix[compatibility matrix].

The https://hibernate.org/community/compatibility-policy/[compatibility policy] may also be of interest.
====

If you get Hibernate NoSQL from Maven Central, it is recommended to import Hibernate Platform
as part of your dependency management to keep all its artifact versions aligned.

Gradle::
[source, groovy, subs="+attributes"]
----
dependencies {
  implementation platform "org.hibernate.nosql:hibernate-platform:{fullVersion}"

  // use the versions from the platform
  implementation "org.hibernate.nosql:hibernate-nosql-core"
  // Use a NoSQL dialect of your choice
  implementation "org.hibernate.nosql:hibernate-neo4j"
  implementation "jakarta.transaction:jakarta.transaction-api"
}
----
Maven::
[source, xml, subs="+attributes"]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.hibernate.nosql</groupId>
            <artifactId>hibernate-platform</artifactId>
            <version>{fullVersion}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
<!-- use the versions from the platform -->
<dependencies>
    <dependency>
        <groupId>org.hibernate.nosql</groupId>
        <artifactId>hibernate-nosql-core</artifactId>
    </dependency>
    <!-- Use a NoSQL dialect of your choice -->
    <dependency>
        <groupId>org.hibernate.nosql</groupId>
        <artifactId>hibernate-neo4j</artifactId>
    </dependency>
    <dependency>
        <groupId>jakarta.transaction</groupId>
        <artifactId>jakarta.transaction-api</artifactId>
    </dependency>
</dependencies>
----

[[compatibility-database]]
=== Database

Hibernate {fullVersion}'s compatibility with a given database and version
depends on the dialect being used.

Refer to the link:{doc-dialect-url}[Dialects] guide for details about both dialects and supported databases.
